name = "Dev Blog"
description = "A simple blog customized for featuring code."
license = "LGPL-3.0-or-later"
min_version = "0.17.2"

[author]
name = "Arthur Araruna"
homepage = "https://dev.araruna.me"

[extra]
my_name = "John Doe"

favicon = ""
site_logo = ""

header = { logo_path = "" }

# Index page's header metadata

meta = [
  { name = "author", content = "Zola - DevBlog Theme" },
  { name = "description", use_config = true },
  { name = "keywords", content = "" },
  { name = "referrer", content = "no-referrer" }
]

link = [
  { rel = "icon", href = "/favicon.ico", type = "image/x-icon" }
]